version: "3"

services:
  nestjs-eval-mcamus:
    image: nestjs-app
    build: .
    volumes:
      - .:/app
    depends_on:
      - db-eval-mcamus
    environment:
      POSTGRES_HOST: db-eval-mcamus
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestjs_db
    ports:
      - "3000:3000"
  db-eval-mcamus:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestjs_db
